# -*- coding: utf-8 -*-
"""conditional_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oPzSiIwbtYGmVa1VUh9KYFtyHBGVDXgf
"""

spending= int(input("How much did you spend?"))

if spending >= 50:
  print("You get 5 percent discount")
else:
  print("sorry, no discount")

spending= int(input("How much did you spend?"))

if spending >= 50 and spending < 100:
  print("You get 5 percent discount")
elif spending >= 100 and spending < 200:
  print("You get 10 percent discount!")
elif spending >=200 and spending < 300:
  print("You get a 25 percent discount, WOW")
elif spending >=300:
  print("You get a 35 perrcent discount!!!!")
else:
  print("sorry, no discount")

spending= int(input("How much did you spend?"))
discount=0
if spending >= 50 and spending < 100:
  print("You get 5 percent discount")
  discount=.05
elif spending >= 100 and spending < 200:
  print("You get 10 percent discount!")
  discount=.10
elif spending >=200 and spending < 300:
  print("You get a 25 percent discount, WOW")
  discount=.25
elif spending >=300:
  print("You get a 35 perrcent discount!!!!")
  discount= 0.35
else:
  print("sorry, no discount")
total=spending-(spending*discount)
print(total)