# -*- coding: utf-8 -*-
"""input_string.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rSturOndZ6t7ZW-pGpdi2CHZPvjoK_WE
"""

name = input("Enter your name : ")
print("Welcome ", name)
print(f"Welcome {name}")

science_scores=int(input("Enter score of science:"))
English_scores=int(input("Enter score of English:"))
math_scores=int(input("Enter score of math:"))

average=(math_scores+science_scores+English_scores)/3

print(f"The average is : {round(average,2)}")

percent=(average/100*100)
print(f"The percentage is : {percent}")

line=input("Write a sentence with 5 words.")
print(line[0])
print(line[1])
print(line[2])
print(line[3])
print(line[4])
print(line[5])
print(line[0:5])
print(line[1:5])
print(line[2:5])
print(line[3:5])
print(line[4:5])

